[package]
name = "website_status_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
ureq = "2.5"
chrono = "0.4"

[dev-dependencies]
mockito = "0.30.0"

